<?php 

include('./admin/includes/connect.php'); // Include the database connection file

// Include the TCPDF library
require_once('./admin/TCPDF-main/tcpdf.php');

// Fetch order and product details
if (isset($_GET['order_id'])) {
    $order_id = $_GET['order_id'];

    // Corrected query with a placeholder for parameter binding
    $query = "SELECT * FROM orders WHERE order_id = ?";
    
    // Prepare the SQL statement
    $stmt = $con->prepare($query);
    
    // Bind the 'order_id' parameter, specifying the type 'i' (integer)
    $stmt->bind_param('i', $order_id);
    
    // Execute the statement
    $stmt->execute();
    
    // Get the result
    $result = $stmt->get_result();
    $order = $result->fetch_assoc();

    if ($order) {
        // Fetch order details
        $product_title = $order['product_title'];
        $price = $order['price'];
        $quantity = $order['quantity'];
        $payment_method = $order['payment_method'];
        $order_date = $order['date'];
        $receiving_date = date('Y-m-d', strtotime($order_date . ' +7 days'));

        // Create a new PDF document
        $pdf = new TCPDF();
        
        // Set document information
        $pdf->SetCreator(PDF_CREATOR);
        $pdf->SetAuthor('Your DA clothes store');
        $pdf->SetTitle('Order Details');

        // Set default header data
        $pdf->SetHeaderData('', 0, 'Order Report', 'Generated by DA clothes store');

        // Set margins
        $pdf->SetMargins(20, 20, 20);

        // Add a page
        $pdf->AddPage();

        // Set font
        $pdf->SetFont('helvetica', '', 12);

        // HTML content for the PDF
        $html = "
            <h2>Order Details</h2>
            <table border='1' cellpadding='5'>
                <tr>
                    <th>Product Title</th>
                    <td>{$product_title}</td>
                </tr>
                <tr>
                    <th>Price</th>
                    <td>$ {$price}</td>
                </tr>
                <tr>
                    <th>Quantity</th>
                    <td>{$quantity}</td>
                </tr>
                <tr>
                    <th>Payment Method</th>
                    <td>{$payment_method}</td>
                </tr>
                <tr>
                    <th>Order Date</th>
                    <td>{$order_date}</td>
                </tr>
                <tr>
                    <th>Receiving Date</th>
                    <td>{$receiving_date}</td>
                </tr>
            </table>
        ";

        // Write the HTML content to the PDF
        $pdf->writeHTML($html, true, false, true, false, '');

        // Output the PDF (Force download)
        $pdf->Output('order_details.pdf', 'D');
    } else {
        echo "Order not found!";
    }
}

?>
